AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 47

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

